const { Router } = require('express');
const urlController = require('../controllers/url.controller');

/**
 * @swagger
 * components:
 *   schemas:
 *     Url:
 *       type: object
 *       required:
 *         - full
 *       properties:
 *         id:
 *           type: string
 *           description: The auto-generated id of the book
 *         full:
 *           type: string
 *           description: The full url to be shortened
 *         short:
 *           type: string
 *           description: A short string that is autogenerated
 *         createdAt:
 *           type: string
 *           format: date
 *           description: The date the Url was created
 *         updatedAt:
 *           type: string
 *           format: date
 *           description: The date the Url data was last modified
 *       example:
 *         id: 0c787260-9db6-46d5-a77a-3ce37cb5ed00
 *         full: https://developer.mozilla.org/en-US/docs/Web/API
 *         short: tg-0-4Fw0
 *         createdAt: 2023-09-05T19:40:48.488Z
 *         updatedAt: 2023-09-05T19:40:48.488Z
 */

const snipperRouter = Router();

/**
 * @swagger
 * tags:
 *   name: Urls
 *   description: The Url managing API
 * /api/snipper:
 *   post:
 *     summary: Create a new url
 *     tags: [Urls]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Url'
 *     responses:
 *       201:
 *         description: The created url.
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Url'
 *       500:
 *         description: Some server error
 *
 */

snipperRouter.post('/', urlController.newUrl);

snipperRouter.get('/', urlController.userUrls);


module.exports = snipperRouter;